version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"
  - package-ecosystem: "bundler"
    directory: "/jekyll"
    schedule:
      interval: "daily"
