language: python
python: 3.6

before_install:
    - nvm install node
    - npm i -g yarn
    - rvm install 2.6.1
    - gem update --system
    - gem install bundler

install:
    - cd _js; yarn install; cd ..
    - bundle install --jobs=3 --retry=3

script: make

deploy:
    - provider: pages
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true
      local-dir: build/dist
      target-branch: gh-pages
      on:
          branch: jekyll
