language: ruby
rvm:
    - 2.5.0-p0

script: jekyll build

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: _site
    target-branch: gh-pages
    on:
        branch: jekyll
