language: ruby
rvm:
    - 2.4.0

before_script:
    - nvm install 7.4.0
    - npm install font-spider -g
    - sed -i "s/cssRule instanceof CSSFontFaceRule/cssRule.constructor.name === 'CSSFontFaceRule'/g" /home/travis/.nvm/versions/node/v7.4.0/lib/node_modules/font-spider/src/spider/index.js

script: bash ./deploy.sh

env:
    global:
        - ENCRYPTION_LABEL: "e4c6db214c19"
        - COMMIT_AUTHOR_EMAIL: "firez199984@gmail.com"
