name:               "c0ldcat's blog"
description:        "一个伪装成菜鸡全栈工程师的上海高三狗"

url:                "//blog.c0ldcat.ml"
author:             "c0ldcat"

baseurl:            ""

markdown:           kramdown

timezone:           Asia/Shanghai

nav:
  - name:           "Posts"
    href:           "/posts"
  - name:           "Projects"
    href:           "/projects"
  - name:           "Tags"
    href:           "/tags"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /posts/:title/
      layout: post

projects:
  - name: Netease Music Java
    description: 网易云音乐 Java API
    link: https://github.com/c0ldcat/netease-music-java
    image: /images/netease-music.svg
  - name: Scale JPG
    description: 一步解决图片大小格式限制问题
    link: https://github.com/c0ldcat/scale-jpg
    image: /images/scale-jpg.svg
  - name: Z Uploader
    description: Group uploader, 收文件专用
    link: https://github.com/c0ldcat/z-uploader
    image: /images/z-uploader.svg
  - name: Hackwlb Server
    description: 本站开源哦
    link: https://github.com/c0ldcat/hackwlb-server
    image: /images/c0ldcat.svg
  - name: Red Music
    description: Bluetooth MP3 with Netease Music
    link: https://github.com/c0ldcat/red-music
    image: /images/red-music.svg
  - name: KR Home Protocol
    description: 点对点式智能家具协议
    link: "#"
    image: /images/kmp.svg
  - name: RopeZ
    description: 厉害的线阵LED跳绳
    link: "#"
    image: /images/rope-z.svg
  - name: Pet Camera
    description: Intel IOT 2015! 超好用的宠物智能拍照神器
    link: https://github.com/c0ldcat/Pet-Camera
    image: /images/pet-camera.svg
  - name: iTool MagicQT Box with LBox Extra
    description: 敬逝去的学习机时代
    link: https://github.com/c0ldcat/Noah-NP2300-LBox
    image: /images/lbox.svg

social:
  - service: github
    username: c0ldcat
    link: https://github.com/c0ldcat
  - service: mail
    username: firez199984@gmail.com
    link: mailto:firez199984@gmail.com

background: /images/background.png

sass:
    sass_dir:         _sass
    style:            :compressed

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

tags_paginate: 10
tags_paginate_path: "/tags/:num"

paginate: 10
paginate_path: "/posts/:num"

gems:
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-paginate

exclude:
  - "*.dot"
  - ".*"
  - "Gemfile"
  - "genGemfile.sh"
  - "deploy.sh"
  - "deploy_key"
  - "deploy_key.enc"
