name: Build Site
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 14
    - name: Setup PNPM
      uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.13.5
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.57.0
      with:
        ruby-version: 2.7.0
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: make install-dependencies
    - name: Build site
      run: make dist
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
        enable_jekyll: false
        keep_files: false
